version: '3'

services:
    client:
        build:
            context: ./
            dockerfile: ./apps/client/Dockerfile
        ports:
            - '5173:80'
            - '5174:443'
        restart: always
        volumes:
            - ./apps/client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./apps/client/certbot/www/:/var/www/certbot/:ro
            - ./apps/client/certbot/conf/:/etc/nginx/ssl/:ro
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./apps/client/certbot/www/:/var/www/certbot/:rw
            - ./apps/client/certbot/conf/:/etc/letsencrypt/:rw
    server:
        build:
            context: ./
            dockerfile: ./apps/server/Dockerfile
        ports:
            - '3000:3000'
    static:
        build:
            context: ./
            dockerfile: ./apps/static/Dockerfile
        ports:
            - '3001:3001'
