export const envKeys = [
    'STATIC_SERVER_HOSTNAME',
    'CLIENT_HOSTNAME',
    'SERVER_PORT',
    'SERVER_REFRESH_TOKEN_EXP_IN_SEC',
    'SERVER_ACCESS_TOKEN_EXP_IN_SEC',
    'SERVER_JWT_SECRET',
] as const;
